### ISSUE TITLE
Errors out when I include dashes in specific text search

### ISSUE THREAD

**Issue by andreaslordos** [ekzhang/classes.wtf#4]
Hi, I love the website and you obviously did an incredible job of engineering it. Just one quip that I thought you might want to look into -- it seems to error out when my query includes a dash (attached screenshot below as an example)

<img width="805" alt="Screen Shot 2022-08-15 at 3 39 36 PM" src="https://user-images.githubusercontent.com/29073065/184732907-c4786f81-301b-40b4-97e2-bb81825fa18c.png">

**Comment by ekzhang** [comment]
Thanks. It's a little bit unintuitive but dashes and punctuation aren't supported by the query engine. They're also not indexed by the full-text search. You can do this search with "first principles" instead.

The reason why it gives an error is because dashes mean something else: negation. You can query for `crypto* -cryptocurrency` for example, or `-@level:{graduate}`.

Maybe since the feature isn't documented I'll just remove all the dashes in the user's query string.
