### ISSUE TITLE
Spams the browser history

### ISSUE THREAD

**Issue by eternaleclipse** [ekzhang/classes.wtf#5]
The title is quite self explanatory - The website spams the browser history, adding a new entry every time the user types a character.

**Comment by ekzhang** [comment]
Thanks for the point of note! It actually doesn't create problems for users with the browser's "back" button, since the website uses the `history.replaceState` API. Unfortunately there's [no way to stop Chrome from adding to the global browser history](https://developer.mozilla.org/en-US/docs/Web/API/History_API/Working_with_the_History_API#:~:text=Note%20that%20this%20doesn%27t%20prevent%20the%20creation%20of%20a%20new%20entry%20in%20the%20global%20browser%20history.) as well with this API.
